In [1]:
import numpy as np
import pandas as pd
from textblob import Word

In [2]:
df_1 = pd.read_csv("symptomsDisease246k.csv")

df_1

,query,response
0,"anxiety and nervousness ,shortness of breath ,...",panic disorder
1,"shortness of breath ,depressive or psychotic s...",panic disorder
2,"anxiety and nervousness ,depression ,shortness...",panic disorder
3,"anxiety and nervousness ,depressive or psychot...",panic disorder
4,"anxiety and nervousness ,depression ,insomnia ...",panic disorder
...,...,...
246940,"diminished hearing ,facial pain ,nosebleed",open wound of the nose
246941,"diminished hearing ,nosebleed",open wound of the nose
246942,"diminished hearing ,nosebleed",open wound of the nose
246943,"diminished hearing ,headache ,nosebleed",open wound of the nose
246944,"diminished hearing ,facial pain",open wound of the nose

In [3]:
word_counts = df_1['response'].value_counts()

minimum = 1100
maximum = 1220
filtered_words = word_counts[(word_counts > minimum) & (word_counts < maximum)]

(filtered_words)

response
cystitis                              1219
vulvodynia                            1218
nose disorder                         1218
complex regional pain syndrome        1217
spondylosis                           1216
hypoglycemia                          1215
peripheral nerve disorder             1215
esophagitis                           1215
vaginal cyst                          1215
conjunctivitis due to allergy         1215
diverticulitis                        1214
gastrointestinal hemorrhage           1214
acute bronchitis                      1213
pneumonia                             1212
fungal infection of the hair          1212
infectious gastroenteritis            1212
spontaneous abortion                  1212
sprain or strain                      1212
gout                                  1211
arthritis of the hip                  1210
strep throat                          1210
marijuana abuse                       1210
injury to the arm                     1209
liver disease                         1209
bursitis                              1208
eczema                                1207
spinal stenosis                       1207
acute pancreatitis                    1207
injury to the leg                     1206
noninfectious gastroenteritis         1206
benign prostatic hyperplasia (bph)    1206
acute bronchiolitis                   1204
cholecystitis                         1204
anxiety                               1198
obstructive sleep apnea (osa)         1196
concussion                            1191
dental caries                         1185
Name: count, dtype: int64

In [6]:
df_1['response'] = df_1['response'].str.strip()

In [9]:
classes = ['response', 'cystitis', 'vulvodynia', 'nose disorder', 'complex regional pain syndrome', 'spondylosis', 'hypoglycemia', 
           'peripheral nerve disorder', 'esophagitis', 'vaginal cyst', 'conjunctivitis due to allergy', 'diverticulitis',
           'gastrointestinal hemorrhage', 'acute bronchitis', 'pneumonia', 'fungal infection of the hair', 'infectious gastroenteritis',
           'spontaneous abortion', 'sprain or strain', 'gout', 'arthritis of the hip', 'strep throat', 'marijuana abuse', 
           'injury to the arm', 'liver disease', 'bursitis', 'eczema', 'spinal stenosis', 'acute pancreatitis', 'injury to the leg']
df_2 = df_1[df_1['response'].isin(classes)]

df_2

                                                  Symptom             Disease
11316          vomiting ,diarrhea ,side pain ,hemoptysis   acute pancreatitis
11317   sharp chest pain ,abusing alcohol ,sharp abdom...  acute pancreatitis
11318   abusing alcohol ,sharp abdominal pain ,nausea ...  acute pancreatitis
11319                                           vomiting   acute pancreatitis
11320   abusing alcohol ,nausea ,diarrhea ,back pain ,...  acute pancreatitis
...                                                   ...                 ...
243955  itching of skin ,skin dryness, peeling, scalin...              eczema
243956                                         skin rash               eczema
243957  skin lesion ,allergic reaction ,itching of ski...              eczema
243958  cough ,abnormal appearing skin ,skin dryness, ...              eczema
243959  cough ,acne or pimples ,itching of skin ,skin ...              eczema

[35158 rows x 2 columns]

In [10]:
df_3 = df_2.reset_index(drop=True)
df_3.dropna()
df_3

                                                 Symptom             Disease
0             vomiting ,diarrhea ,side pain ,hemoptysis   acute pancreatitis
1      sharp chest pain ,abusing alcohol ,sharp abdom...  acute pancreatitis
2      abusing alcohol ,sharp abdominal pain ,nausea ...  acute pancreatitis
3                                              vomiting   acute pancreatitis
4      abusing alcohol ,nausea ,diarrhea ,back pain ,...  acute pancreatitis
...                                                  ...                 ...
35153  itching of skin ,skin dryness, peeling, scalin...              eczema
35154                                         skin rash               eczema
35155  skin lesion ,allergic reaction ,itching of ski...              eczema
35156  cough ,abnormal appearing skin ,skin dryness, ...              eczema
35157  cough ,acne or pimples ,itching of skin ,skin ...              eczema

[35158 rows x 2 columns]

In [9]:
misspelled_words = df_3[df_3['response'] != df_3['response'].apply(lambda x: Word(x).correct())]

# Count the number of misspelled words
misspelled_count = misspelled_words['response'].nunique()

print("Number of unique misspelled words:", misspelled_count)

Number of unique misspelled words: 0

In [11]:
df_3.columns.values[0] = 'Symptom'
df_3.columns.values[1] = 'Disease'

In [12]:
#word_counts = df_3['response'].value_counts()

#print(word_counts)

In [14]:
df_3.to_csv('New_Cleaned_Dataset6.0.csv', index=True)